#!/usr/bin/env bash

echo "Turning on vim syntax highlighting..."
echo 'syntax on' >> $HOME/.vimrc
echo 'set tabstop=2' >> $HOME/.vimrc
echo 'set shiftwidth=2' >> $HOME/.vimrc
echo 'set expandtab' >> $HOME/.vimrc

echo 'Installing vim-airline vim plugin...'

if [ ! -d "$HOME/.vim/pack/plugins/start/vim-airline/" ]; then
  git clone https://github.com/vim-airline/vim-airline.git $HOME/.vim/pack/plugins/start/vim-airline
  echo 'OK'
fi

echo 'Installing NERD_tree vim plugin...'

if [ ! -d "$HOME/.vim/pack/plugins/start/NERD_tree/" ]; then
  curl -o /tmp/NERD_tree.zip http://www.vim.org/scripts/download_script.php?src_id=23731
  unzip -q /tmp/NERD_tree.zip -d $HOME/.vim/pack/plugins/start/NERD_tree/
  rm /tmp/NERD_TREE.zip
  echo 'OK'
fi

echo 'Updating ~/.gitconfig...'
git config --global color.ui auto
echo 'OK'

echo 'Please login to the AppStore then hit <ENTER>'
echo '30s timeout before continuing...'
read -n 1 -s -t 30

echo 'Installing Mac AppStore apps...'
# 1Password
mas install 443987910
# Microsoft Remote Desktop
mas install 715768417
# Slack
mas install 803453959
# Magnet
mas install 441258766
# Update apps that need them
mas upgrade
echo 'OK'

echo 'Setting up Chef...'
if [ ! -d "$HOME/git/chef-repo" ]; then
  git clone git@github.com:daptiv/chef-repo.git $HOME/git/chef-repo
fi

knife configure --defaults -s https://manage.chef.io/organizations/daptiv -r $HOME/git/chef-repo
echo 'OK'

# echo 'Environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY must be set prior to'
# echo 'running Strap.  If this is already done hit <ENTER>, otherwise exit and set these variables'
# echo 'before running Strap.'
# echo '10s timeout before continuing...'
# read -n 1 -s -t 10

# echo 'Setting up AWS keys...'
# if [ ! -d "$HOME/git/ops_rolaids" ]; then
  # git clone git@github.com:daptiv/ops_rolaids.git $HOME/git/ops_rolaids
# fi

# sh $HOME/git/ops_rolaids/assume_role.sh cicd && unset AWS_SECRET_ACCESS_KEY && unset AWS_ACCESS_KEY_ID

# aws ssm get-parameters-by-path --path "/amazon/keys/" | jq --raw-output '.[][] .Name'
# echo 'OK'

echo 'Prior to moving *.pem from ~/Downloads please ensure all relevant'
echo '"GO_AWS_*" pem files are downloaded from Password Safe.'
echo '10s timeout before continuing...'
read -n 1 -s -t 10

mv $HOME/Downloads/*.pem $HOME/.ssh/
chmod 444 $HOME/.ssh/*.pem

