#!/usr/bin/env bash

echo 'Turning on vim syntax highlighting...'
echo 'syntax on' >> $HOME/.vimrc
echo 'set tabstop=2' >> $HOME/.vimrc
echo 'set shiftwidth=2' >> $HOME/.vimrc
echo 'set expandtab' >> $HOME/.vimrc

echo 'Installing vim-airline vim plugin...'

if [ ! -d "$HOME/.vim/pack/plugins/start/vim-airline/" ]; then 
  git clone https://github.com/vim-airline/vim-airline.git $HOME/.vim/pack/plugins/start/vim-airline
  echo 'OK'
fi

echo 'Installing NERD_tree vim plugin...'

if [ ! -d "$HOME/.vim/pack/plugins/start/NERD_tree/" ]; then
  curl -o /tmp/NERD_tree.zip http://www.vim.org/scripts/download_script.php?src_id=23731
  unzip -q /tmp/NERD_tree.zip -d $HOME/.vim/pack/plugins/start/NERD_tree/
  rm /tmp/NERD_TREE.zip
  echo 'OK'
fi

echo 'Installing Mac AppStore apps...'
# 1Password
mas install 443987910
# Microsoft Remote Desktop
mas install 715768417
# Slack
mas install 803453959
# Magnet
mas install 441258766
# Update apps that need them
mas upgrade
