#!/usr/bin/env bash

ensure_dotfile_link() {
  HOMEFILE="$HOME/$1"
  DOTFILE="$(pwd -P)"
  
  if [ -L "$HOMEFILE" ] && ! [ -d "$DOTFILE" ]; then
    ln -sfv "$DOTFILE" "$HOMEFILE"
  else
    rm -rv "$HOMEFILE"
    ln -sv "$DOTFILE" "$HOMEFILE"
  fi
}

ensure_dotfile_link .bash_profile
ensure_dotfile_link .bashrc
ensure_dotfile_link .Brewfile

# install spotify

curl https://download.spotify.com/Spotify.dmg -o ~/Downloads/Spotify.dmg
hdiutil attach ~/Downloads/Spotify.dmg
ditto /Volumes/Spotify/Spotify.app /Applications/Spotify.app
diskutil unmount Spotify
rm ~/Downloads/Spotify.dmg

